amazonProperties:
   endpointUrl: https://s3.ap-south-1.amazonaws.com
   accessKey: AKIASI7IRSJD5TCKQQDJ
   secretKey: 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
   bucketName: strongerme-asset
   region: ap-south-1